=== Bangojetty/lifeburn/Data/CardSchema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"title": "Card",
	"type": "object",
	"properties": {
		"id": {
			"type": "integer"
		},
		"name": {
			"type": "string"
		},
		"cost": {
			"type": "integer"
		},
		"type": {
			"$ref": "DefinitionSchema.json#/cardType"
		},
		"attack": {
			"type": "integer"
		},
		"defense": {
			"type": "integer"
		},
		"keywords": {
			"type": "array",
			"items": {
				"$ref": "DefinitionSchema.json#/keyword"
			}
		},
		"tribe": {
			"$ref": "DefinitionSchema.json#/tribe"
		},
		"rarity": {
			"type": "string",
			"enum": [ "common", "uncommon", "rare" ]
		},
		"description": {
			"type": "string"
		},
		"stackEffects": {
			"type": "array",
			"items": {
				"$ref": "EffectSchema.json"
			}
		},
		"triggeredEffects": {
			"type": "array",
			"items": {
				"$ref": "TriggerSchema.json"
			}
		},
		"passiveEffects": {
			"type": "array",
			"items": {
				"$ref": "PassiveSchema.json"
			}
		},
		"activatedEffects": {
			"type": "array",
			"items": {
				"$ref": "ActiveSchema.json"
			}
		},
		"costModifiers": {
			"type": "array",
			"items": {
				"$ref": "CostModifierSchema.json"
			}
		},
		"additionalCosts": {
			"type": "array",
			"items": {
				"$ref": "AdditionalCostSchema.json"
			}
		},
		"alternateCosts": {
			"type": "array",
			"items": {
				"$ref": "AlternateCostSchema.json"
			}
		},
		"castRestrictions": {
			"type": "array",
			"items": {
				"type": "string",
				"enum": ["onOpponentAttack", "inResponse", "opponentsTurn", "controlGoblin"]
			}
		}
	}
}

=== Bangojetty/lifeburn/LifeServer/Data/Cards/181_Channel.json
{
  "id": 181,
  "name": "Channel",
  "cost": 0,
  "type": "spell",
  "tribe": "goblin",
  "rarity": "common",
  "description": "Deal {X} damage to target player. Channel cannot reduce players below 1 LP",
  "costModifiers": [
    {
      "modifier": "x",
      "additionalModifier": "+10"
    }
  ],
  "stackEffects": [
    {
      "effect": "dealDamage",
      "target": {
        "type": "player"
      },
      "amountBasedOn": "x",
      "restrictions": [
        "cantReduceBelowOne"
      ]
    }
  ]
}

=== Bangojetty/lifeburn/Data/Cards/234_RitualOfDarkness.json
{
  "id": 234,
  "name": "Ritual Of Darkness",
  "cost": 11,
  "type": "spell",
  "tribe": "shadow",
  "rarity": "rare",
  "description": "Starting with you, each player may put a summon into play. Repeat until no player puts a summon into play.",
  "stackEffects": [
    {
      "effect": "cardRitualOfDarkness"
    }
  ]
}

=== Bangojetty/lifeburn/Data/Cards/269_GoblinLieutenant.json
{
  "id": 269,
  "name": "Goblin Lieutenant",
  "cost": 0,
  "type": "summon",
  "attack": 1,
  "defense": 1,
  "keywords": ["blitz"],
  "tribe": "goblin",
  "rarity": "common",
  "description": "When Goblin Lieutenant attacks, create an attacking 3/1 goblin until end of turn.",
  "triggeredEffects": [  
    {
      "trigger": "attack",
      "scope": "selfOnly",
      "effects": [
        {
          "effect": "createToken",
          "tokenType": "goblin",
          "attack": 3,
          "defense": 1,
          "amount": 1,
          "attacking": true,
          "tokenPassive": {
				"passive": "thisTurn"
		    }
        }
      ] 
    }
  ]
}

=== Bangojetty/lifeburn/Data/Cards/064_MerfolkShifter.json
{
  "id": 64,
  "name": "Merfolk Shifter",
  "cost": 1,
  "type": "summon",
  "attack": 3,
  "defense": 2,
  "keywords": ["dive"],
  "tribe": "merfolk",
  "rarity": "common",
  "description": "When Merfolk Shifter enters play, return target summon to its owner's hand.",
  "triggeredEffects": [
	  {
		"trigger": "enteredZone",
		"zone": "play",
		"effects": [
		  {
			"effect": "sendToZone",
			"targetType": "summon",
			"destination": "hand"
		  }
		]  
	  }
    ] 
}

=== Bangojetty/lifeburn/LifeServer/Data/Cards/076_Snag.json
{
  "id": 76,
  "name": "Snag",
  "cost": 3,
  "type": "spell",
  "tribe": "merfolk",
  "rarity": "common",
  "description": "Return target summon to its owner's hand. Gain 1 LP.",
  "stackEffects": [
    {
      "effect": "sendToZone",
      "target": {
        "type": "summon"
      },
      "destination": "hand"
    },
    {
      "effect": "gainLife",
      "amount": 1
    }
  ]
}

=== Bangojetty/lifeburn/Data/Cards/019_MoltenGravel.json
{
  "id": 19,
  "name": "Molten Gravel",
  "cost": 1,
  "type": "summon",
  "attack": 0,
  "defense": 0,
  "keywords": ["blitz"],
  "tribe": "golem",
  "rarity": "common",
  "description": "Molten Gravel gets +1/+1 for each stone you control. If you have 10 or more stones, Molten Gravel has trample.",
  "passiveEffects": [
    {
      "passive": "changeStats",
	  "statModifiers": [
		{
		  "statType": "attack",
		  "operatorType": "add",
		  "amountBasedOn": "stonesControlled"
		},
		{
		  "statType": "defense",
		  "operatorType": "add",
		  "amountBasedOn": "stonesControlled"
		}
	  ],
	  "scope": "selfOnly"
    },
    {
      "conditions": [
        {
          "condition": "control",
          "tokenType": "stone",
          "minAmount": 10
        }
      ],
      "passive": "grantKeyword",
      "keyword": "trample",
	  "scope": "selfOnly"
    }
  ]
}

=== Bangojetty/lifeburn/LifeServer/Data/Cards/245_PutridFolks.json
{
  "id": 245,
  "name": "Putrid Folks",
  "cost": 0,
  "type": "summon",
  "attack": 0,
  "defense": 2,
  "tribe": "merfolk",
  "rarity": "common",
  "description": "This summon can only be played in response to an opponents attack. When Putrid Folks enters play, exile target summon until your next draw phase",
  "castRestrictions": [
    "onOpponentAttack"
  ],
  "triggeredEffects": [
    {
      "trigger": "enteredZone",
      "zone": "play",
      "effects": [
        {
          "effect": "exileAndReturn",
          "target": {
            "type": "summon"
          },
          "duration": "drawPhase"
        }
      ]
    }
  ]
}

=== Bangojetty/lifeburn/LifeServer/Data/Cards/051_MerfolkGazer.json
{
  "id": 51,
  "name": "Merfolk Gazer",
  "cost": 0,
  "type": "summon",
  "attack": 0,
  "defense": 1,
  "tribe": "merfolk",
  "rarity": "common",
  "description": "When Merfolk Gazer enters play, opponents reveal their hands.",
  "triggeredEffects": [
  {
    "trigger": "enteredZone",
    "zone": "play",
    "effects": [
      {
        "effect": "reveal",
        "sourcePlayer": "opponent"
      }
    ]
  }
  ]
}
