=== Bangojetty/lifeburn/Data/CardSchema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"title": "Card",
	"type": "object",
	"properties": {
		"id": {
			"type": "integer"
		},
		"name": {
			"type": "string"
		},
		"cost": {
			"type": "integer"
		},
		"type": {
			"$ref": "DefinitionSchema.json#/cardType"
		},
		"attack": {
			"type": "integer"
		},
		"defense": {
			"type": "integer"
		},
		"keywords": {
			"type": "array",
			"items": {
				"$ref": "DefinitionSchema.json#/keyword"
			}
		},
		"tribe": {
			"$ref": "DefinitionSchema.json#/tribe"
		},
		"rarity": {
			"type": "string",
			"enum": [ "common", "uncommon", "rare" ]
		},
		"description": {
			"type": "string"
		},
		"stackEffects": {
			"type": "array",
			"items": {
				"$ref": "EffectSchema.json"
			}
		},
		"triggeredEffects": {
			"type": "array",
			"items": {
				"$ref": "TriggerSchema.json"
			}
		},
		"passiveEffects": {
			"type": "array",
			"items": {
				"$ref": "PassiveSchema.json"
			}
		},
		"activatedEffects": {
			"type": "array",
			"items": {
				"$ref": "ActiveSchema.json"
			}
		},
		"costModifiers": {
			"type": "array",
			"items": {
				"$ref": "CostModifierSchema.json"
			}
		},
		"additionalCosts": {
			"type": "array",
			"items": {
				"$ref": "AdditionalCostSchema.json"
			}
		},
		"alternateCosts": {
			"type": "array",
			"items": {
				"$ref": "AlternateCostSchema.json"
			}
		},
		"castRestrictions": {
			"type": "array",
			"items": {
				"type": "string",
				"enum": ["onOpponentAttack", "inResponse", "opponentsTurn", "controlGoblin"]
			}
		}
	}
}

=== Bangojetty/lifeburn/Data/Cards/173_Smite.json
{
  "id": 173,
  "name": "Smite",
  "cost": 3,
  "type": "spell",
  "tribe": "goblin",
  "rarity": "common",
  "description": "Deal 3 damage to any target. If you control a Goblin, deal 4 instead.",
  "stackEffects": [
    {
      "effect": "dealDamage",
      "targetType": "any",
      "amount": 3,
      "amountModifier": "+1",
      "modifierConditions": [
        {
          "condition": "control",
          "tribe": "goblin",
          "minAmount": 1
        }
      ]
    }
  ]
}

=== Bangojetty/lifeburn/LifeServer/Data/Cards/225_Grow.json
{
  "id": 225,
  "name": "Grow",
  "cost": 7,
  "type": "spell",
  "tribe": "treefolk",
  "rarity": "common",
  "description": "Cast a treefolk summon from your hand or graveyard without paying it's cost. Create an herb.",
  "stackEffects": [
    {
      "effect": "castCard",
      "targetType": "cardInHandOrGraveyard",
      "cardType": "summon",
      "tribe": "treefolk"
    },
    {
      "effect": "createToken",
      "tokenType": "herb",
      "amount": 1
    }
  ]
}

=== Bangojetty/lifeburn/Data/Cards/096_DuskWraith.json
{
  "id": 96,
  "name": "Dusk Wraith",
  "cost": 0,
  "type": "summon",
  "attack": 1,
  "defense": 1,
  "tribe": "shadow",
  "rarity": "common",
  "description": "When Dusk Wraith is milled, destroy target summon. If you can't, gain 3 LPs.",
  "triggeredEffects": [
    {
      "trigger": "mill",
      "scope": "selfOnly",
      "description": "Destroy target summon. If you can't, gain 3 LPs.",
      "effects": [
        {
          "effect": "destroy",
          "targetType": "summon",
          "conditions": [{ "condition": "summonsInPlay" }]
        },
        {
          "effect": "gainLife",
          "amount": 3,
          "conditions": [{ "condition": "noSummonsInPlay" }]
        }
      ]
    }
  ]
}

=== Bangojetty/lifeburn/LifeServer/Data/Cards/135_ExchangeSouls.json
{
  "id": 135,
  "name": "Exchange Souls",
  "cost": 6,
  "type": "spell",
  "tribe": "shadow",
  "rarity": "common",
  "description": "Mill 1. Return a summon from your graveyard to play.",
  "stackEffects": [
    {
      "effect": "mill",
      "amount": 1
    },
    {
      "effect": "sendToZone",
      "target": {
        "type": "cardInGraveyard"
      },
      "cardType": "summon",
      "destination": "play",
      "resolveTarget": true
    }
  ]
}

=== Bangojetty/lifeburn/Data/Cards/025_BrassGolem.json
{
  "id": 25,
  "name": "Brass Golem",
  "cost": 2,
  "type": "summon",
  "attack": 1,
  "defense": 1,
  "tribe": "golem",
  "rarity": "common",
  "description": "When Brass Golem enters play, create a golem with attack and defense equal to the number of stones you control.",
  "triggeredEffects": [
    {
      "trigger": "enteredZone",
      "zone": "play",
      "effects": [
        {
          "effect": "createToken",
          "tokenType": "golem",
          "attackBasedOn": "stonesControlled",
          "defenseBasedOn": "stonesControlled",
		  "description": "create a golem with attack and defense equal to the number of stones you control."
       }
      ]
    }
  ]
}

=== Bangojetty/lifeburn/Data/Cards/029_Quarry.json
{
  "id": 29,
  "name": "Quarry",
  "cost": 3,
  "type": "object",
  "tribe": "golem",
  "rarity": "common",
  "description": "At the beginning of your draw phase, create a stone. \n Sacrifice any number of stones: Draw that many cards, then sacrifice Quarry.",
  "triggeredEffects": [
	{
	  "trigger": "phase",
	  "phase": "draw",
	  "effect": "createToken",
	  "tokenType": "stone",
	  "amount": 1
	}
  ],
  "activatedEffects": [
  {
    "costType": "sacrifice",
	"tokenType": "stone",
    "playerChosenAmount": true,
    "effects": [
      {
        "effect": "draw",
        "amountBasedOn": "activatedCost"
      },
      {
        "effect": "sacrifice",
		"self": true
      }
    ]
  }
  ]
}

=== Bangojetty/lifeburn/Data/Cards/146_TransparentGoblin.json
{
  "id": 146,
  "name": "Transparent Goblin",
  "cost": 0,
  "type": "summon",
  "attack": 1,
  "defense": 1,
  "tribe": "goblin",
  "rarity": "common",
  "description": "Transparent Goblin does not count as your summon for turn.",
  "passiveEffects": [
    {  
      "passive": "bypassSummonLimit"
    }
  ] 
}

=== Bangojetty/lifeburn/LifeServer/Data/Cards/271_GoblinTactician.json
{
  "id": 271,
  "name": "Goblin Tactician",
  "cost": 0,
  "type": "summon",
  "attack": 1,
  "defense": 1,
  "tribe": "goblin",
  "rarity": "common",
  "description": "When Goblin Tactician enters play, you may put a +1/+1 counter on target goblin. \n Sacrifice Goblin Tactician: deal its power to any target.",
  "triggeredEffects": [
    {
      "trigger": "enteredZone",
      "zone": "play",
      "optional": true,
      "optionMessage": "Put a +1/+1 counter on a goblin?",
      "effects": [
        {
          "effect": "addCounter",
          "counterType": "oneOne",
          "targetType": "summon",
          "tribe": "goblin"
        }
      ]
    }
  ],
  "activatedEffects": [
    {
      "costType": "sacrifice",
      "scope": "selfOnly",
      "effects": [
        {
          "effect": "dealDamage",
          "targetType": "any",
          "amountBasedOn": "finalAttack",
          "description": "Deal damage equal to Goblin Tactician's power."
        }
      ]
    }
  ]
}
