=== Bangojetty/lifeburn/Data/CardSchema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"title": "Card",
	"type": "object",
	"properties": {
		"id": {
			"type": "integer"
		},
		"name": {
			"type": "string"
		},
		"cost": {
			"type": "integer"
		},
		"type": {
			"$ref": "DefinitionSchema.json#/cardType"
		},
		"attack": {
			"type": "integer"
		},
		"defense": {
			"type": "integer"
		},
		"keywords": {
			"type": "array",
			"items": {
				"$ref": "DefinitionSchema.json#/keyword"
			}
		},
		"tribe": {
			"$ref": "DefinitionSchema.json#/tribe"
		},
		"rarity": {
			"type": "string",
			"enum": [ "common", "uncommon", "rare" ]
		},
		"description": {
			"type": "string"
		},
		"stackEffects": {
			"type": "array",
			"items": {
				"$ref": "EffectSchema.json"
			}
		},
		"triggeredEffects": {
			"type": "array",
			"items": {
				"$ref": "TriggerSchema.json"
			}
		},
		"passiveEffects": {
			"type": "array",
			"items": {
				"$ref": "PassiveSchema.json"
			}
		},
		"activatedEffects": {
			"type": "array",
			"items": {
				"$ref": "ActiveSchema.json"
			}
		},
		"costModifiers": {
			"type": "array",
			"items": {
				"$ref": "CostModifierSchema.json"
			}
		},
		"additionalCosts": {
			"type": "array",
			"items": {
				"$ref": "AdditionalCostSchema.json"
			}
		},
		"alternateCosts": {
			"type": "array",
			"items": {
				"$ref": "AlternateCostSchema.json"
			}
		},
		"castRestrictions": {
			"type": "array",
			"items": {
				"type": "string",
				"enum": ["onOpponentAttack", "inResponse", "opponentsTurn", "controlGoblin"]
			}
		}
	}
}

=== Bangojetty/lifeburn/LifeServer/Data/Cards/045_Calculate.json
{
  "id": 45,
  "name": "Calculate",
  "cost": 0,
  "type": "spell",
  "tribe": "merfolk",
  "rarity": "common",
  "description": "Choose one: \n {c0}-Counter target summon with 1 defense and lose 2 LPs. \n {c0}-Counter target spell with 2 or less LP cost and lose 2 LPs. \n {c0}-Draw a card.",
  "stackEffects": [
    {
      "effect": "choose",
      "choiceIndex": 0,
      "choices": [
        [
          {
            "effect": "counter",
            "target": {
              "type": "summon"
            },
            "restrictions": [
              "defense"
            ],
            "restrictionMax": 1,
            "restrictionMin": 1
          },
          {
            "effect": "loseLife",
            "amount": 2
          }
        ],
        [
          {
            "effect": "counter",
            "target": {
              "type": "spell"
            },
            "restrictions": [
              "cost"
            ],
            "restrictionMax": 2
          },
          {
            "effect": "loseLife",
            "amount": 2
          }
        ],
        [
          {
            "effect": "draw",
            "amount": 1
          }
        ]
      ]
    }
  ]
}

=== Bangojetty/lifeburn/LifeServer/Data/Cards/053_MerfolkRusher.json
{
  "id": 53,
  "name": "Merfolk Rusher",
  "cost": 0,
  "type": "summon",
  "attack": 4,
  "defense": 3,
  "tribe": "merfolk",
  "rarity": "common",
  "description": "When Merfolk Rusher enters play, sacrifice it unless you return a merfolk you control to your hand.",
  "triggeredEffects": [
    {
      "trigger": "enteredZone",
      "zone": "play",
      "scope": "selfOnly",
      "effects": [
        {
          "effect": "choose",
          "choices": [
            [
              {
                "effect": "sacrifice",
                "scope": "selfOnly"
              }
            ],
            [
              {
                "effect": "sendToZone",
                "target": {
                  "type": "summon"
                },
                "tribe": "merfolk",
                "destination": "hand"
              }
            ]
          ]
        }
      ]
    }
  ]
}

=== Bangojetty/lifeburn/Data/Cards/255_Rewind.json
{
  "id": 255,
  "name": "Rewind",
  "cost": 0,
  "type": "spell",
  "tribe": "merfolk",
  "rarity": "uncommon",
  "description": "Rewind can only be played in response to another spell, and only during your opponents turn. Counter all spells on the stack. Your opponent restarts their turn.",
  "castRestrictions": ["inResponse", "opponentsTurn"], 
  "stackEffects": [
    {
      "effect": "counter",
      "all": true 
    },
    {
      "effect": "goToPhase",
      "phase": "draw",
      "isOpponent": true
    }
  ] 
}

=== Bangojetty/lifeburn/LifeServer/Data/Cards/137_CrawlBack.json
{
  "id": 137,
  "name": "Crawl Back",
  "cost": 3,
  "type": "spell",
  "tribe": "shadow",
  "rarity": "common",
  "description": "Return target shadow summon with cost 3 or less from your graveyard to play.",
  "stackEffects": [
    {
      "effect": "sendToZone",
      "target": {
        "type": "cardInGraveyard"
      },
      "cardType": "summon",
      "tribe": "shadow",
      "destination": "play",
      "restrictions": [
        "cost"
      ],
      "restrictionMax": 3
    }
  ]
}

=== Bangojetty/lifeburn/LifeServer/Data/Cards/175_Gamble.json
{
  "id": 175,
  "name": "Gamble",
  "cost": 3,
  "type": "spell",
  "tribe": "goblin",
  "rarity": "common",
  "description": "Draw 3. Opponents draws 2.",
  "stackEffects": [  
    {
      "effect": "draw",
      "amount": 3
    },
    {
      "effect": "draw",
      "sourcePlayer": "opponent",
      "amount": 2
    }
  ]
}

=== Bangojetty/lifeburn/Data/Cards/235_Spectralize.json
{
  "id": 235,
  "name": "Spectralize",
  "cost": 4,
  "type": "spell",
  "tribe": "shadow",
  "rarity": "common",
  "description": "Exile target summon and return it to play. Give it Spectral. If it's a ghost, gain 2 LPs",
  "stackEffects": [
    {
      "effect": "exileAndReturn",
      "targetType": "summon",
      "additionalEffects": [
        {
          "effect": "grantKeyword",
          "keyword": "spectral" 
        },
        {
          "conditions": [
            {
              "condition": "rootTargetTribe",
              "tribe": "shadow"
            }
          ],
          "effect": "gainLife",
          "amount": 2
        }
      ]
    }
  ]
}

=== Bangojetty/lifeburn/Data/Cards/083_CounterBalance.json
{
  "id": 83,
  "name": "Counter Balance",
  "cost": 3,
  "type": "spell",
  "tribe": "merfolk",
  "rarity": "common",
  "description": "Counter target spell. If that spell was a non-summon, its controller gains LPs equal to its cost or draws a card.",
  "stackEffects": [
  {
    "effect": "counter",
    "additionalEffects": [
      {
        "condition": "targetNotSummon",
        "effects": [
          {
            "effect": "choose",
            "playerBasedOn": "ownerOfTarget",
		    "choiceIndex": 0,
            "choices": [
              {
                "effect": "gainLife",
                "playerBasedOn": "ownerOfTarget", 
                "amountBasedOn": "targetCost"
              },
              {
                "effect": "draw",
                "playerBasedOn": "ownerOfTarget",
                "amount": 1  
              }
            ] 
          }
        ] 
      }
    ] 
  }
  ] 
}

=== Bangojetty/lifeburn/LifeServer/Data/Cards/118_Shade.json
{
  "id": 118,
  "name": "Shade",
  "cost": 1,
  "type": "summon",
  "attack": 2,
  "defense": 2,
  "tribe": "shadow",
  "rarity": "common",
  "description": "When Shade enters play, create a 2/2 ghost. Mill half your deck rounded down.",
  "triggeredEffects": [
  {
    "trigger": "enteredZone",
    "zone": "play",
    "effects": [
      {
        "effect": "createToken",
        "tokenType": "ghost",
        "attack": 2,
        "defense": 2,
        "amount": 1 
      },
      {
        "effect": "mill",
        "amountBasedOn": "deckSize",
        "amountModifier": "/2down" 
      }
    ]
  }
  ]
}
